Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1536, in __call__
  File "client.py", line 170, in <lambda>
  File "client.py", line 64, in sendfile
IOError: [Errno 22] invalid mode ('rb') or filename: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1536, in __call__
  File "client.py", line 171, in <lambda>
  File "client.py", line 77, in refresh
error: [Errno 10053] 
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1536, in __call__
  File "client.py", line 103, in make_bold
  File "Tkinter.pyc", line 3196, in tag_names
TclError: text doesn't contain any characters tagged with "sel"
Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyc", line 1536, in __call__
  File "client.py", line 58, in print_item
  File "Tkinter.pyc", line 2623, in get
TclError: bad listbox index "": must be active, anchor, end, @x,y, or a number
